<?php View::content() ?>
<script>
	tinymce.init({
		selector:'textarea', 
		plugins: "table print preview fullpage fullscreen insertdatetime lists",
		tools: "inserttable print code preview fullpage fullscreen insertdatetime"
	});
	$(document).ready(function(){
		$("#guardar_normal").click(function(){
			var text = $("#html");
			var ati = $( "span:contains('Para:')")
			console.log(ati.parent().html())
		})
	});
</script>
<?php echo Form::open() ?>
<div class="well">
	<div class="btn-group" role="group" aria-label="">
		<input type="button" name="guardar_normal" id="guardar_normal" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="Guardar">
		<input type="submit" name="formato" class="btn btn-default"  value="Guardar en Formato">
	</div>
	<br>
	<?php echo Html::link("formato/ver","Lista de Formatos") ?> | <?php echo Html::link("formato/nuevo","Nuevo Formato") ?>
</div>
	<textarea name="documento[html]" id="html" style="height:800px"><?php if (isset($_POST['documento']['html']) and !empty($_POST['documento']['html'])): ?>
		<?php echo $_POST['documento']['html'] ?>
	<?php endif ?></textarea>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Datos de Documento</h4>
      </div>
      <div class="modal-body">
       	<div class="form-group">
       		<label>Para:</label>
       		<input type="text" name="documento[para]" class="form-control input-sm">
       	</div>
       	<div class="form-group">
       		<label>De:</label>
       		<input type="text" name="documento[de]" class="form-control input-sm">
       	</div>
       	<div class="form-group">
       		<label>Asunto:</label>
       		<input type="text" name="documento[asunto]" class="form-control input-sm">
       	</div>
       	<div class="form-group">
       		<label>Fecha:</label>
       		<input type="text" name="documento[fecha_doc]" class="form-control input-sm">
       	</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <input type="submit" value="Guardar" class="btn btn-success">
      </div>
    </div>
  </div>
</div>
</form>